### ISSUE TITLE
For Tabel 1 and prune ratio

### ISSUE THREAD

**Issue by Feng-Hong** [NUS-HPC-AI-Lab/InfoBatch#16]
The prune ratio in your code seems to be only for samples where the loss is less than the mean? Is this unfair to other methods that prune across all samples (Tab. 1)?

If the comparison is fair, i.e. infobatch's prune ratio is also calculated for all samples, how is the 70% prune ratio achieved, since you keep all samples where the loss is greater than average?

**Comment by Yeez-lee** [comment]
> The prune ratio in your code seems to be only for samples where the loss is less than the mean? Is this unfair to other methods that prune across all samples (Tab. 1)?
> 
> If the comparison is fair, i.e. infobatch's prune ratio is also calculated for all samples, how is the 70% prune ratio achieved, since you keep all samples where the loss is greater than averag

Same Question. Based on the method and codes, if prune ratio is 70%, the overall prune ratio could be less than 70% since the pruning is only for samples where the loss is less than the mean.

**Comment by henryqin1997** [comment]
1. The prune ratio calculated is divided by the total data amount. 30% prune ratio is actually below the default prune ratio, because cross entropy loss has a skewed distribution with mean larger than median.
2. 70% pruning ratio can be achieved in two ways to control the computation. As marked in the caption, one way is to control the epoch number. Another way is more complex, instead of using the mean as the pruning threshold, one can use multiple quantiles (percentile threshold, like 30%, 50%, 75% threshold) with multiple pruning ratios. This part of code will be updated soon, and we will add more discussion of this part in the updated version (in Feb).
